# Copyright (c) 2018-2020 Jeron Aldaron Lau
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0>, the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, or the ZLib
# license <LICENSE-ZLIB or https://www.zlib.net/zlib_license.html> at
# your option. This file may not be copied, modified, or distributed
# except according to those terms.

[package]
name = "twang"
version = "0.3.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
license = "MIT OR Apache-2.0 OR Zlib"
documentation = "https://docs.rs/twang"
homepage = "https://github.com/AldaronLau/twang"
repository = "https://github.com/AldaronLau/twang"
readme = "README.md"
description = "Library for pure Rust advanced audio synthesis."
keywords = ["audio", "synth", "synthesizer", "wave", "sound"]
categories = ["multimedia::audio", "multimedia"]
edition = "2018"

[dependencies]
fon = "0.1"
