# Copyright Jeron Aldaron Lau 2018 - 2020.
# Distributed under either the Apache License, Version 2.0
#    (See accompanying file LICENSE_APACHE_2_0.txt or copy at
#          https://apache.org/licenses/LICENSE-2.0),
# or the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_BOOST_1_0.txt or copy at
#          https://www.boost.org/LICENSE_1_0.txt)
# at your option. This file may not be copied, modified, or distributed except
# according to those terms.

[package]
name = "twang"
version = "0.5.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
license = "Apache-2.0 OR BSL-1.0"
documentation = "https://docs.rs/twang"
homepage = "https://github.com/AldaronLau/twang"
repository = "https://github.com/AldaronLau/twang"
readme = "README.md"
description = "Library for pure Rust advanced audio synthesis."
keywords = ["audio", "synth", "synthesizer", "wave", "sound"]
categories = ["multimedia::audio", "multimedia"]
edition = "2018"

[dependencies]
fon = "0.3"

# [replace]
# "fon:0.2.0" = { path = "../fon" }
