# Copyright (c) 2018-2020 Jeron Aldaron Lau
#
# Dual-licensed under either the MIT License or the Boost Software License,
# Version 1.0.  (See accompanying file LICENSE_1_0.txt or copy at
# https://www.boost.org/LICENSE_1_0.txt)

[package]
name = "twang"
version = "0.2.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
license = "MIT OR Apache-2.0 OR Zlib"
documentation = "https://docs.rs/twang"
homepage = "https://github.com/AldaronLau/twang"
repository = "https://github.com/AldaronLau/twang"
readme = "README.md"
description = "Synthesize original sounds in pure Rust."
keywords = ["audio", "synth", "synthesizer", "wave", "sound"]
categories = ["multimedia::audio", "multimedia"]
edition = "2018"

[dependencies]

[dev-dependencies]
cala = { version = "0.8", features = ["speaker"] }
