# Twang
# Copyright © 2018-2021 Jeron Aldaron Lau.
#
# Licensed under any of:
#  - Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
#  - MIT License (https://mit-license.org/)
#  - Boost Software License, Version 1.0 (https://www.boost.org/LICENSE_1_0.txt)
# At your choosing (See accompanying files LICENSE_APACHE_2_0.txt,
# LICENSE_MIT.txt and LICENSE_BOOST_1_0.txt).

[package]
name = "twang"
version = "0.7.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
license = "Apache-2.0 OR MIT OR BSL-1.0"
documentation = "https://docs.rs/twang"
homepage = "https://github.com/AldaronLau/twang/blob/main/CHANGELOG.md"
repository = "https://github.com/AldaronLau/twang"
readme = "README.md"
description = "Library for pure Rust advanced audio synthesis."
keywords = ["audio", "synth", "synthesizer", "wave", "sound"]
categories = ["multimedia::audio", "multimedia", "algorithms", "mathematics"]
edition = "2018"
include = ["Cargo.toml", "src/*"]

[dependencies]
fon = "0.5"
